site_name: Zephyr RTOS Development Course
site_url: https://tinegachris.github.io/course_zephyr_rtos_rpi_4b/
theme:
  name: material
plugins:
  - git-revision-date-localized
nav:
  - 'Home': 'README.md'
  - 'Contributing':
    - 'Code of Conduct': 'CONDUCT.md'
    - 'Contributing': 'CONTRIBUTING.md'
  - 'Chapter 1: Course Introduction': 'chapter_01_course_introduction/introduction.md'
  - 'Chapter 2: Introduction to Zephyr':
    - 'Introduction': 'chapter_02_introduction_to_zephyr/introduction.md'
    - 'Theory': 'chapter_02_introduction_to_zephyr/theory.md'
    - 'Lab': 'chapter_02_introduction_to_zephyr/lab.md'
  - 'Chapter 3: Zephyr Build System':
    - 'Introduction': 'chapter_03_zephyr_build_system/introduction.md'
    - 'Theory': 'chapter_03_zephyr_build_system/theory.md'
    - 'Lab': 'chapter_03_zephyr_build_system/lab.md'
  - 'Chapter 4: Configure Zephyr':
    - 'Introduction': 'chapter_04_configure_zephyr/introduction.md'
    - 'Theory': 'chapter_04_configure_zephyr/theory.md'
    - 'Lab': 'chapter_04_configure_zephyr/lab.md'
  - 'Chapter 5: West':
    - 'Introduction': 'chapter_05_west/introduction.md'
    - 'Theory': 'chapter_05_west/theory.md'
    - 'Lab': 'chapter_05_west/lab.md'
  - 'Chapter 6: Zephyr Fundamentals':
    - 'Introduction': 'chapter_06_zephyr_fundamentals/introduction.md'
    - 'Theory': 'chapter_06_zephyr_fundamentals/theory.md'
    - 'Lab': 'chapter_06_zephyr_fundamentals/lab.md'
  - 'Chapter 7: Thread Management':
    - 'Introduction': 'chapter_07_thread_management/introduction.md'
    - 'Theory': 'chapter_07_thread_management/theory.md'
    - 'Lab': 'chapter_07_thread_management/lab.md'
  - 'Chapter 8: Tracing and Logging':
    - 'Introduction': 'chapter_08_tracing_and_logging/introduction.md'
    - 'Theory': 'chapter_08_tracing_and_logging/theory.md'
    - 'Lab': 'chapter_08_tracing_and_logging/lab.md'
  - 'Chapter 9: Memory Management':
    - 'Introduction': 'chapter_09_memory_management/introduction.md'
    - 'Theory': 'chapter_09_memory_management/theory.md'
    - 'Lab': 'chapter_09_memory_management/lab.md'
  - 'Chapter 10: User Mode':
    - 'Introduction': 'chapter_10_user_mode/introduction.md'
    - 'Theory': 'chapter_10_user_mode/theory.md'
    - 'Lab': 'chapter_10_user_mode/lab.md'
  - 'Chapter 11: Traditional Multithreading Primitives':
    - 'Introduction': 'chapter_11_traditional_multithreading_primitives/introduction.md'
    - 'Theory': 'chapter_11_traditional_multithreading_primitives/theory.md'
    - 'Lab': 'chapter_11_traditional_multithreading_primitives/lab.md'
  - 'Chapter 12: Inter-thread Communication':
    - 'Introduction': 'chapter_12_inter-thread_communication/introduction.md'
    - 'Theory': 'chapter_12_inter-thread_communication/theory.md'
    - 'Lab': 'chapter_12_inter-thread_communication/lab.md'
  - 'Chapter 13: Interrupt Management':
    - 'Introduction': 'chapter_13_interrupt_management/introduction.md'
    - 'Theory': 'chapter_13_interrupt_management/theory.md'
    - 'Lab': 'chapter_13_interrupt_management/lab.md'
  - 'Chapter 14: Modules':
    - 'Introduction': 'chapter_14_modules/introduction.md'
    - 'Theory': 'chapter_14_modules/theory.md'
    - 'Lab': 'chapter_14_modules/lab.md'
  - 'Chapter 15: Writing Kconfig Symbols':
    - 'Introduction': 'chapter_15_writing_kconfig_symbols/introduction.md'
    - 'Theory': 'chapter_15_writing_kconfig_symbols/theory.md'
    - 'Lab': 'chapter_15_writing_kconfig_symbols/lab.md'
  - 'Chapter 16: Device Driver Architecture':
    - 'Introduction': 'chapter_16_device_driver_architecture/introduction.md'
    - 'Theory': 'chapter_16_device_driver_architecture/theory.md'
    - 'Lab': 'chapter_16_device_driver_architecture/lab.md'
  - 'Chapter 17: Power Management':
    - 'Introduction': 'chapter_17_power_management/introduction.md'
    - 'Theory': 'chapter_17_power_management/theory.md'
    - 'Lab': 'chapter_17_power_management/lab.md'
  - 'Chapter 18: Capstone Project':
    - 'Introduction': 'chapter_18_capstone_project/introduction.md'
    - 'Theory': 'chapter_18_capstone_project/theory.md'
    - 'Lab': 'chapter_18_capstone_project/lab.md'
    - 'Networked Monitor': 'chapter_18_capstone_project/networked_monitor/README.md'