name: deploy

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
    - main

permissions:
  pages: write
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-github-pages.outputs.page_url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin

    - name: Build the book
      run: mkdocs build

    - name: Deploy to GitHub Pages
      id: deploy-to-github-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
